name: 'Smoke Tests'

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
  pull_request:

jobs:
  smoke_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '14'

      - name: Install operating system dependencies
        run: npx playwright install-deps

      - run: npm install

      # This is needed otherwise will error if playwright is updated
      - run: npx playwright install

      - name: Run tests
        env:
          SENTRY_DSN: ${{secrets.SENTRY_DSN}}
        run: npm test
