name: 'Smoke Tests'

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
  pull_request:

jobs:
  smoke_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '14'

      - name: Install operating system dependencies
        run: npx playwright install-deps

      - run: npm install

      # This is needed otherwise will error if playwright is updated
      - run: npx playwright install

      - name: Run tests
        env:
          SENTRY_SMOKE_USER: ${{ secrets.SENTRY_SMOKE_USER }}
          SENTRY_SMOKE_PASSWORD: ${{ secrets.SENTRY_SMOKE_PASSWORD }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: npm test

      # This may cause double reporting if assertions in `sentryio.spec.ts`
      # fail, but we want to capture errors that happen outside of the test
      # file itself where the Sentry SDK is initialized. Reports to
      # https://sentry.io/organizations/sentry/issues/?project=5992455
      #
      # TODO: Send some better logs to Sentry
      - name: Report CI to Sentry
        if: failure()
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: |
          curl -sL https://sentry.io/get-cli/ | bash
          sentry-cli send-event -m "smoke test ci job failed (look at https://github.com/getsentry/smoke-test-sentry/actions)"

      # Upload artifacts to GHA only on failures, as we don't care if it passes
      - uses: actions/upload-artifact@v3.1.1
        if: always()
        with:
          name: trace
          path: test-results
          retention-days: 7
